### ISSUE TITLE
Improve styling on mobile

### ISSUE THREAD

**Issue by adydetra** [nuxt/nuxt.com#1385]
`Table`

![image](https://github.com/nuxt/nuxt.com/assets/108399634/76cd351c-c0fb-4dfc-b833-86b567894ef9)

---

Maybe is `inline code`?

![image](https://github.com/nuxt/nuxt.com/assets/108399634/7c856422-eb69-493c-988d-0f562462c80b)

**Comment by Mat4m0** [comment]
## For Table:
Tested on site: https://nuxt.com/docs/api/commands/build
### Before
<img width="350" alt="image" src="https://github.com/nuxt/nuxt.com/assets/79974907/932e2f3a-f499-47e3-9779-acd09fa62faa">

### After
Changing the table prose from `word-break: break-all` to `word-break: normal` and it looks way better.

```css
.prose :where(table):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
        ...
	word-break: normal;
}
```

<img width="350" alt="image" src="https://github.com/nuxt/nuxt.com/assets/79974907/69d031cb-6249-435e-bafb-0e8888a852b0">

I checked multiple sites with the setting enabled, and it looks good on my side (tested with Firefox latest), it just needs to be checked if this property can be safely applied to all tables.

In the [standard tailwind styles ](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js) there is no `word-break` to be found inside. 

## For Inline Code:
Just saw today on [Twitter Aaron Francis](https://twitter.com/aarondfrancis/status/1729982234977882381) had the same issue. Solution was also posted there, so many thanks ;)

To make it look better, it could be improved with [Box-decoration-break set to clone](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break)

Tested on site: https://nuxt.com/docs/getting-started/introduction#server-side-rendering

### Before

<img width="350" alt="image" src="https://github.com/nuxt/nuxt.com/assets/79974907/ed2937e3-83b9-4295-88e2-844dc49bb13b">

### Box-Decoration-break
```css
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
        ...
	box-decoration-break: clone;
}
```
<img width="350" alt="image" src="https://github.com/nuxt/nuxt.com/assets/79974907/6f3c03ab-5dbe-4533-8026-8052fdfa6802">

Looks better, but still not perfect with the border decoration starting on the previous line 😬

### Inline Block

The best result I got was with changing to `display: inline-block` and then removing the vertical padding.

```css
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
        ...
	padding: 0rem .375rem;
	display: inline-block;
}
```

<img width="350" alt="image" src="https://github.com/nuxt/nuxt.com/assets/79974907/05922d3f-b30c-4a8c-8be7-1d546f4a6f4d">
