### ISSUE TITLE
Improve setup steps on deploying Nuxt app to AWS Amplify on docs

### ISSUE THREAD

**Issue by idorenyinudoh** [nuxt/nuxt.com#1439]
# Affected page
https://nuxt.com/deploy/aws-amplify

# Description
The documentation states that the integration of a Nuxt 3 app with AWS Amplify requires zero configuration. But that is not the case and I'll explain why.

The default build config that AWS Amplify generates is this:
```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 18
        - corepack enable
        - npx --yes nypm i
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
```

However, Nuxt's build (and generate) command generates an `.output` directory that contains the app's contents ready to be served.

Hence, the `baseDirectory` property in Amplify's build config will need to be updated to `.output/public`. Hence, Nuxt's integration with AWS Amplify isn't zero config.

Happy to open a PR.

P.S: [Nitro's docs](https://nitro.unjs.io/deploy/providers/aws-amplify) might be misleading as well.
